### ISSUE TITLE
Update libbeat doc

### ISSUE THREAD

**Issue by monicasarbu** [elastic/libbeat#100]
Common documentation for all beats is moved to libbeat (see #98).
Things that need to be updated in the beats common documentation:
   - [x] Update output plugins to both support TLS via host configuration and optionally config file.
   - [x] Add Lumberjack output 
   - [x] Document GeoIP configuration and requirement to use GeoIP City database.
   - [x] Document which cipher suites are not recommend (see commend @jordansissel in https://github.com/elastic/libbeat/pull/124)

**Comment by monicasarbu** [comment]
Would be nice to add a few info about how the agents can load balance the data to Logstash.

**Comment by urso** [comment]
all done.
