### ISSUE TITLE
Selective fields + conditional

### ISSUE THREAD

**Issue by monicasarbu** [elastic/libbeat#111]
It would be nice to be able to select/choose the fields that you want to export to Elasticsearch. For example, for a HTTP request you don't want to export all headers and only a specific header. Additionally, it would be nice to be able to choose to export more fields for errors. In case the status code is greater than 200, export all the info about the transaction.

Requested https://discuss.elastic.co/t/input-filtering-on-fields-or-bpf-filter-before-sending-to-elastic/26716/5

**Comment by McStork** [comment]
+1

**Comment by ruflin** [comment]
Closing in favor of the filtering proposal here: https://github.com/elastic/libbeat/issues/336
