### ISSUE TITLE
Allow paths with wildcard directories

### ISSUE THREAD

**Issue by roji** [elastic/libbeat#117]
In some cases log files are grouped into subdirectories, and it seems impossible to specify the following for logstash-forwarder: /syslog/log/**/*.

This capability is supported by logstash, see this conversation.

(Issue copied from https://github.com/elastic/logstash-forwarder/issues/532)

**Comment by ruflin** [comment]
@roji Somehow this issue ended up in libbeat instead of filebeat. Can I ask you again to move it there? https://github.com/elastic/filebeat

**Comment by roji** [comment]
Apologies, I opened this too quickly. Opened https://github.com/elastic/filebeat/issues/68 instead.

**Comment by ruflin** [comment]
@roji Thanks.
