### ISSUE TITLE
Restrict event type

### ISSUE THREAD

**Issue by urso** [elastic/libbeat#125]
Restrict event value types to some basic types for use with filters.

**Comment by ruflin** [comment]
@urso can you add some more details here? This also relates to https://github.com/elastic/libbeat/issues/336?

**Comment by urso** [comment]
Yes, this somehow relates to #336.

At the moment events basically are map[string]interface{} with any JSON-serializable type being usable as field content. I have 3 problems with this representation. First is: if we want to generate 'simplified' events for filtering we heavily depend on reflection (or have to transform to simplfied event type).  Second: default golang json/encoder is known not to be the fastest for having to deal with reflection. Third: required/special fields must be set in map and are queried multiple times for being correct (e.g. @timestamp).

e.g. (without notes on internal representation (which can be 'optimized' later?):

    type Event struct {
        ...
    }

    type EventBuilder func(...) error

    func NewEvent(ts *time.Time, ...EventBuilder) *Event {
        ...
    }

    type (e *Event) uint(name string, u uint) {
        ...
    }

    type (e *Event) int(name string, i int) {
        ...
    }

    type (e *Event) str(name string, value string) {
        ...
    }

    type (e *Event) add(name string, sub *Event) {
        ...
    }

    type (e *Event) getT(name string) T {
    }

    // event builders:

    // use reflection to set fields
    func Value(name string, i interface{}) EventBuilder

    func Number(name string, n int64) EventBuilder

    func Str(name string, v string) EventBuilder

    func Nested(name string, ...EventBuilder) EventBuilder



    // create new Event:

    NewEvent(time.Now(),
      Str("file", fileName),
      Number("offset", offset),
      Str("message", line),
      Nested("fields",
              ...))

Maybe not as convenient as using maps all the way down, but this on gives us 'strongly typed' events + JSON serialization should be very straight forward and 'fast'.

**Comment by andrewkroh** [comment]
I like the proposal. It also brings immutability to events.

**Comment by ruflin** [comment]
Closing this to continue discussion in https://github.com/elastic/beats/issues/923
