### ISSUE TITLE
Fail to configure localhost:9200 as ES node

### ISSUE THREAD

**Issue by monicasarbu** [elastic/libbeat#142]
To be backwards compatible, we need to be able to accept IP:PORT in the hosts config option. If the IP is a string then it fails.

The config file:

      output:
          elasticsearch:
          enabled: true
          hosts: ["localhost:9200"]

You can easily check that by adding a unit test for "localhost:9200".

**Comment by ruflin** [comment]
Thanks for spotting. That is bad. I checked for everything except the "default" :-( https://github.com/elastic/libbeat/blob/master/outputs/elasticsearch/output_test.go#L341
