### ISSUE TITLE
Update gettingstarted guide to remove redis requirement for logstash

### ISSUE THREAD

**Issue by urso** [elastic/libbeat#152]
With next beta redis is not required for logstash + redis might be deprecated. Update gettingstarted doc on logstash usage.

**Comment by tsg** [comment]
Ideally we would update [this page](https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-logstash.html) to use the new plugin, move it in libbeat and link it from all other guides.

If there is no time, we should at least delete that page as ti might confuse folks.
