### ISSUE TITLE
Wrong default configuration file

### ISSUE THREAD

**Issue by monicasarbu** [elastic/libbeat#155]
If topbeat is installed from deb package, then when starting it without passing a config file throws an err:

vagrant@precise32:~$ topbeat -e -d "publish"
Failed to read /etc/beat/beat.yml: open /etc/beat/beat.yml: no such file or directory. Exiting.

We should be able to start topbeat without any configuration file and consider a default like /etc/topbeat/topbeat.yml for Topbeat.

**Comment by tsg** [comment]
Probably libbeat is not up to date. I'll take care.
