### ISSUE TITLE
Add direction field to publisher output to indicate inbound/outbound transactions

### ISSUE THREAD

**Issue by rshriram** [elastic/libbeat#157]
Given a request/response between two microservices where packetbeat is installed, the outputs (esp. ip and client_ip fields) emitted at both source and destination are alike. This makes it hard to distinguish where the transaction originated from. 

Setting ignore_outgoing to true is not necessarily the solution, as it results in loss of useful information. When ignore_outgoing is set to false, the response time recorded at the source gives an indication of network RTT + destination's processing time, while response time recorded at the destination indicates the processing time for a particular request. Comparing these two gives the user an idea of where the latency for a request is coming from: network or the remote server?.

I have submitted PR #150  that addresses this issue, by adding a direction field to the output.

**Comment by ruflin** [comment]
Closing as #150 was merged.
