### ISSUE TITLE
Update link to Beats input in Logstash

### ISSUE THREAD

**Issue by monicasarbu** [elastic/libbeat#172]
The doc about the Beats input in Logstash doesn't exists yet. So, it's better to remove it and add it later when it's there.

The link is set to in the getting started guide of libbeat:
http://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html

**Comment by urso** [comment]
link in getting started guide points to github repository. Once documentaion becomes available, link will be updated.
