### ISSUE TITLE
Add Beats to Deb and RPM elastic Repositories

### ISSUE THREAD

**Issue by ruflin** [elastic/libbeat#209]
Add the stable releases of Topbeat, Packetbeat and Filebeat to the elasticsearch deb and rpm repositories: https://www.elastic.co/blog/apt-and-yum-repositories

Here is the script from elasticsearch adding files to the repository: https://github.com/elastic/elasticsearch/blob/master/dev-tools/prepare_release_candidate.py

This should probably happen as part of beats-packer: https://github.com/elastic/beats-packer

**Comment by ruflin** [comment]
This is also related to: https://github.com/elastic/packetbeat/issues/259

**Comment by andrewkroh** [comment]
I signed our past RPM releases and pushed them to packages.elasticsearch.org. You can install the repo with the following commands.

```
rpm --import https://packages.elasticsearch.org/GPG-KEY-elasticsearch
curl -o /etc/yum.repos.d/beats.repo http://packages.elasticsearch.org/beats/yum/el/beats.repo
```

Remaining work:

- [ ] Update beats-packer to sign new releases and publish them to packages.elasticsearch.org.
- [ ] Figure out how to sign/publish debian packages (never done this before) and publish past releases.
- [ ] Determine if we need a yum and apt repo for nightlies. (?)

**Comment by ruflin** [comment]
Tested on CentOS and works :+1: 

I suggest no yum repo for nightlies. If you use nightlies, you should definitively know what you are doing and install it by hand.

**Comment by andrewkroh** [comment]
I signed out past debian release and pushed them. You can install and test with the following commands:

```
curl https://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add -
echo "deb http://packages.elasticsearch.org/beats/apt stable main" |  tee -a /etc/apt/sources.list
apt-get update
apt-get install topbeat filebeat packetbeat
```

**Comment by ruflin** [comment]
Commands tested on Debian 8. Installation works.

**Comment by andrewkroh** [comment]
I have the beats-packer updated locally with new make target `package-upload`. It signs the .deb and .rpm files in beats-packer's `build/upload` directory and pushes them to packages.elastic.co. 

This process requires the Elastic GPG signing key. I want to discuss key management briefly before I push out a PR.

**Comment by ruflin** [comment]
@andrewkroh :+1: We should probably also include @spinscale into the discussion.

**Comment by andrewkroh** [comment]
We (whole Beats team) decided during our Friday call to use git-crypt to store a copy of the signing key in a non-public repo.

Closing because all issue have been addressed in other PRs.
