### ISSUE TITLE
Throw an warning if the beat cannot output to the specified file

### ISSUE THREAD

**Issue by monicasarbu** [elastic/libbeat#212]
Requested by https://discuss.elastic.co/t/is-it-possible-to-write-to-dev-stdout-using-file-output/32935

**Comment by mrkschan** [comment]
Tried adding `fmt.Println(err)` to https://github.com/elastic/libbeat/blob/ffe7593ae3f037997dce5568be9e08e7f09821d2/outputs/fileout/file.go#L86, I get `rename /dev/stdout /dev/stdout.1: permission denied`.

There are two problems here i guess.

1. The error is not printed even I use `-d '*'` debug selector.
2. FileRotator always rotate an existing file after "restart". (Is this expected behavior?)

Though, I don't think "/dev/stdout" should be handled by file rotator.

**Comment by ruflin** [comment]
@mrkschan https://github.com/elastic/libbeat/pull/215/files should fix the logging issue. 
If a file exist, it is currently rotate on startup. If it doesn't a new one is created.

`/dev/stdout` should definitively not handled by file rotator. I suggest when you need this as an output to open a new issue with a feature request.

**Comment by mrkschan** [comment]
@ruflin thx for the quick patch. Where should I open a feature request? Should I do it right here in Github or just leave it on discuss.elastic.co?

**Comment by ruflin** [comment]
For feature requests you can directly use Github.

**Comment by mrkschan** [comment]
BTW, shall `topbeat` handle the `error` returned from `PublishEvent`? https://github.com/elastic/topbeat/blob/7e42a733d568f3e62da53bb7c3feff39ca840b9c/topbeat.go#L158

And `filebeat`... https://github.com/elastic/filebeat/blob/89410957be0163fe2e999cab0efffdeb6ab926c5/beat/filebeat.go#L131

**Comment by ruflin** [comment]
In the case of filebeat definitively. For topbeat I think it would be good behaviour to at least state, in case the error is ignored. @urso What do you think?

**Comment by urso** [comment]
In case of filebeat: yes

In case of topbeat: yes and no. Depends on what you'd expect. In case we implement sync output for topbeat: If outputer is  unresponsive for long enough, the publisher code might block due queues filling up. When queues fill up, topbeat won't be able to create new events and samples will be lost. At least queues provide some buffering potentially given is an ok time window to recover, though. In async mode (currently used), sending is retried 3 times by default. If it fails data is lost. In either case samples might get lost.
