### ISSUE TITLE
Accept stdout as file output

### ISSUE THREAD

**Issue by monicasarbu** [elastic/libbeat#218]
Requested here: https://discuss.elastic.co/t/is-it-possible-to-write-to-dev-stdout-using-file-output/32935

We need to add a special behavior if the file is /dev/stdout.

**Comment by urso** [comment]
rather have special stdout output plugin. Then we don't have to add logic to file outputer

**Comment by ruflin** [comment]
Agree with @urso. Stdout should be a separate output and not part of the file output.

**Comment by urso** [comment]
Thanks for agreeing, just finished ;)
