### ISSUE TITLE
Change -e option to send the logging messages to stderr instead of stdout

### ISSUE THREAD

**Issue by monicasarbu** [elastic/libbeat#219]
Currently when the "-e" option is used in the command line of each beat, the logging messages are sent to stdout as it becomes easier to grep for them. If they would have been sent to stderr, then you need to use  -e 2>&1 | grep ... which in the end it's ok. 

Sending the logging messages to stderr seems to be a better approach here as it fulfills users' expectations.

Requested by: https://discuss.elastic.co/t/is-it-intended-to-log-errors-to-stdout-while-calling-the-option-in-the-code-stderr/33082

**Comment by ruflin** [comment]
Closing based on https://github.com/elastic/libbeat/pull/221
