### ISSUE TITLE
TLS insecure option is ignored for logstash

### ISSUE THREAD

**Issue by tsg** [elastic/libbeat#238]
It seems that the tls configuration is copied over in the transport [Connect](https://github.com/elastic/libbeat/blob/master/outputs/logstash/transport.go#L103) function. Not sure about the motivation behind this copy, but the problem is that the `InsecureSkipVerify` option is not copied over.

This breaks the insecure option. Should be an easy fix.

**Comment by urso** [comment]
will add tests

**Comment by tsg** [comment]
Test is tracked in #240.
