### ISSUE TITLE
Update the latest stable version of Kibana and ES

### ISSUE THREAD

**Issue by monicasarbu** [elastic/libbeat#241]
Currently the documentation advise you to install Elasticsearch 1.7.2, Kibana 4.1.2 and Logstash 1.5.4. As Elasticsearch 2.0.0, Kibana 4.2.0 and Logstash 2.0.0 were released we need to update getting started guide (at least) with the newest versions.

* [x] update libbeat/index.asciidoc with the latest versions
* [x] check if the steps described in getting started guide still work (especially if the links are still working)

**Comment by monicasarbu** [comment]
@dedemorton can you please have a look?

**Comment by dedemorton** [comment]
@monicasarbu Quick question: is this change relevant to beta4, too? Just want to make sure that I am working in the correct branch. I'm working in the beta4 branch still with the assumption that everything is going to get pushed into Master. Is that correct.

**Comment by monicasarbu** [comment]
@dedemorton yes, you can change the versions in beta4 as well.  All the docs related commits will be merged to Master today by @tsg.

**Comment by dedemorton** [comment]
@monicasarbu  This is essentially resolved by PR #257. 

However, the deb and rpm steps need to be tested. And the paths for Elasticsearch will need to be updated  when the infra team resolves the related issue described here: https://github.com/elastic/infra/issues/548

So I will keep this open for now.

**Comment by monicasarbu** [comment]
@dedemorton Thanks! We will do some testing for deb and rpm.

**Comment by monicasarbu** [comment]
Close this issue for now. A new task (called Check getting started steps) is added to the things that need to be tested manually for each release, available in the `beats-qa` repository.
