### ISSUE TITLE
Logs are always written to stderr

### ISSUE THREAD

**Issue by urso** [elastic/libbeat#276]
Even if logging to stderr is not explicitly configured on command line, logs are still written to stderr.

On startup (before setting up) stderr is enabled by default: https://github.com/elastic/libbeat/blob/master/logp/logp.go#L88

SetStderr must be called to disable stderr logging after setup. This is only done by packetbeat, but no other beat.

**Comment by ruflin** [comment]
I would suggest to disable it by default in libbeat instead of delegating this task to the beats.

**Comment by andrewkroh** [comment]
I think the call to `SetStderr` can be inserted here: https://github.com/elastic/libbeat/blob/master/beat/beat.go#L128

@urso @ruflin Do you agree?
