### ISSUE TITLE
long download paths create double scroll bars in the doc

### ISSUE THREAD

**Issue by dedemorton** [elastic/libbeat#277]
The very long paths for downloading Elasticsearch cause double scroll bars in the HTML output from ASCIIdoc:

https://www.elastic.co/guide/en/beats/libbeat/current/getting-started.html#elasticsearch-installation

We could possibly tweak the css to fix this problem, but even so, the path would be hard to read, so I've opened an issue against infrastructure to get the download path shortened. https://github.com/elastic/infra/issues/548

**Comment by ruflin** [comment]
@dedemorton I assume that is a general and not only beats specific problem? Thanks for pushing that forward.

**Comment by dedemorton** [comment]
Possibly...if there are other places in the doc that show installing from the command line. At any rate, it looks like the infra team has already taken care of the problem, and I can update the doc accordingly.
