### ISSUE TITLE
Consolidate beat fields (hostname, name, ip, etc.)

### ISSUE THREAD

**Issue by tsg** [elastic/libbeat#281]
### Current state

First, to summarize the current situation:

* Currently libbeat adds the `shipper` field in all beats, which by default is equal to the host name on which the beat is running on, but it can be overwritten with anything the user wants from the configuration file.

* Logstash-Forwarder used to include the hostname in a `host` field. There is this Filebeat [ticket](https://github.com/elastic/filebeat/issues/208) about losing the compatibility with LSF from this point of view.

This issue has made us realize that the `shipper` field is confusing and the behavior of defaulting to the hostname but make it possible to change it makes it difficult to use across the different beats. In addition, we realized that in the future we are likely to need more fields to identify a beat, like a UUID or the IP address for where it's sending data.

### Plan for the future

Our ideal future situation is that each Beats exports several related fields grouped in a "beat" sub-dictionary:

* beat
  * name (by default the hostname, but changable from the configuration file)
  * hostname (old default shipper value) -> cannot be overwritten in config
  * version
  * uuid
  * ip 
  * type (packetbeat/filebeat/topbeat)

The sub-dictionary is there to group the fields together but also to avoid conflicts with the fields of various Beats. For example, Packetbeat already has and `ip` field.

### Plan for the next release

For `1.0.0-rc2`/`1.0.0-ga`, we plan the following changes:

 * Add the `beat.hostname` field, always set to the hostname as returned by the operating system
 * Rename `shipper` into `beat.name`l.
 * Add the `beat.version` field, because it's easy to add and we are sure it will be useful.

The rest of the fields we don't want to add for GA because we're not yet sure about the format or if they are actually needed. The IP was excluded for now because of difficulties in selecting the right IP address in case more are configured. But since we have the "beat" namespace reserved, we can easily add them later.

The `beat.hostname` is not directly compatible with the LSF, but it can be easily renamed via a Logstash filter when required.

**Comment by tsg** [comment]
There's a bit of a complication because the shipper name is used by the topology management. So we have to keep the logic regarding the publisher name at some level, otherwise we'll likely brake behavior people rely on. Code wise, I'm thinking to have:

<pre>
type PublisherType struct {
	shipperName    string // Shipper name as set in the configuration file
	hostName       string // Host name as returned by the operation system
	name           string // The shipperName if configured, the hostName otherwise
    ....
</pre>

Then in the output fields, `beat.name == shipperName` and `beat.hostname == hostName`.

The `name` is not exported in fields but it's used in the topology map handling.

The other option is to always output a `beat.name`, which would also be more backwards compatible, at the cost at extra disk space.

**Comment by ruflin** [comment]
shipperName only has to be published if topology is enabled, right? So I would go for option two an also export name.

I would call the variable hostname instead of hostName.

**Comment by tsg** [comment]
We don't have to publish the shipperName explicitly in the regular documents, but we do need a name to insert in the `packetbeat-topology` docs. It might be also useful in the future to always have a `beat.name` field, so I'm think I'm leaning towards option two as well. Just that in so many cases it will be equal to the `beat.hostname` that it feels a bit wasteful. It will be less of an issue after we'll be able to filter out the fields via config.
