### ISSUE TITLE
Timestamp and caller are missing when logging to file

### ISSUE THREAD

**Issue by ruflin** [elastic/libbeat#291]
Log output to stderr looks as following:

```
2015/11/12 09:03:37.369262 geolite.go:52: WARN Couldn't load GeoIP database
```

File output for the same event:
```
WARN Couldn't load GeoIP database
```

For stderr, the timestamp is set through flags (https://github.com/elastic/libbeat/blob/master/logp/log.go#L142) so it is automatically generated afterwards. Same for syslog. For file output it must be generated manually. The applies to the caller reference.

For reference also see: https://github.com/elastic/filebeat/issues/223

**Comment by ruflin** [comment]
@nheath Here is a fix for the problem. Can you have a look at the docs change and let me know if that is what you expected? https://github.com/elastic/libbeat/pull/299/files

**Comment by nheath** [comment]
Thanks, diff and docs look good :)
