### ISSUE TITLE
Beats documentation organization results in a fragmented user experience

### ISSUE THREAD

**Issue by dedemorton** [elastic/libbeat#294]
We currently document all common configuration and command line options for the Beats in the  Platform Reference. This makes maintaining the information easier, but it's not an optimal user experience because users need to jump back and forth between the Platform Ref and the Beat-specific doc to find the information that they're looking for. With reference information, retrievability is an important concern. We need to find a better way so that we can avoid duplicating the content, but still provide a satisfactory user experience.

Single sourcing the shared content and making it available where relevant is a viable option that's worth considering.

**Comment by dedemorton** [comment]
Here's a good example. Imagine wanting to run something from the command line in Packetbeat, and here is what you find when you search for help:
https://www.elastic.co/guide/en/beats/packetbeat/current/_command_line_options.html

Would you even go to the Platform Reference to see the detailed explanations of the common CLI options? Probably not. You'd just run packetbeat -h.

**Comment by ruflin** [comment]
@dedemorton We have now a libbeat script with which we sync common files to the beats. In case we decide to have part of the libbeat content with every beat, this would be doable. We would still only have to update the content in one place. Is this an option from your point of view?

**Comment by dedemorton** [comment]
@ruflin Sure, though I'd like to understand more about how this would work. I would expect ASCIIdoc to have some functionality that we could leverage for reusing content (ASCIIdoc is a strange new world for me). 

Before discussing implementation, we probably should decide if it's a good idea to make the content available in the doc for each Beat. A lot of thought has already gone into the current structure. I don't want to rehash old decisions, but I do think the user experience is a bit fragmented. @tbragin has expressed this concern, too.

**Comment by ruflin** [comment]
@dedemorton I agree that we should make every beat doc independent. From a technical point it makes a lot of sense to separate it, but must users are only interested in a beat and don't know about the rest. So I think we should definitively have for example all config options and all command line flags of libbeat also in the beats itself. I still see the need for a general beats space where we have community beats, how to develop a beat etc, but this part is more focused on people that want to develop new beats.

About the implementation question: I'm quite sure whatever we decide, we will find a way to implement it :-)

**Comment by dedemorton** [comment]
+1

**Comment by tbragin** [comment]
I would love to understand whether using snippets is possible to avoid content duplication, but still produce self-contained guides for every beat. Jumping from one guide to another is not ideal - I still have trouble finding.  @dedemorton do you know?

If not, we need to improve cross-linking between documents, though cross-linking still has the drawback that the use is redirected to the right section, but doesn't know when it's appropriate to stop reading the doc and get back to the place he was redirect from. 

An example of where cross-linking would need to get improved is configuration options: 
* packetbeat reference clearly states that shipper config options are in a separate doc
* filebeat reference does redirect you there, but it's not clearly indicated you are taking to a separate doc, so it's confusing
* topbeat does not have a configuration options section at all, but i assume that the shipper config options still apply to it?


<img width="888" alt="screen shot 2015-11-14 at 1 30 02 pm" src="https://cloud.githubusercontent.com/assets/933397/11163552/416cfe62-8ad4-11e5-93eb-e1bc660f9f27.png">
<img width="925" alt="screen shot 2015-11-14 at 1 29 40 pm" src="https://cloud.githubusercontent.com/assets/933397/11163553/4181c388-8ad4-11e5-9680-a2105fdbe6ba.png">
<img width="876" alt="screen shot 2015-11-14 at 1 30 16 pm" src="https://cloud.githubusercontent.com/assets/933397/11163551/4128ee84-8ad4-11e5-8eaf-cbe17b481f7b.png">

**Comment by dedemorton** [comment]
@tbragin  Totally agree with you. I've been focused on low-level edits but plan to make a structural pass early next week to address the issues that you mention and make sure that users can find what they need more easily.

**Comment by monicasarbu** [comment]
I would suggest to add all 4 configuration sections from libbeat to all the Beats, preferably in the same order: Shipper, Output, Logging (Optional) and Run options (Optional). Here is the link: https://www.elastic.co/guide/en/beats/libbeat/current/configuration.html

Beside these 4 sections, we would need to add the Beat specific configurations:
For Packetbeat: Interfaces, Protocols, Processes (Optional)
For Topbeat: Input (maybe not a good name as it's different from Filebeat)
For Filebeat: Filebeat

@tbragin Thank you for bringing it up. I agree that is a bit confusing for the user.

**Comment by dedemorton** [comment]
@ruflin @monicasarbu I spoke with Deb and Paul about content reuse in asciidoc. They suggested putting the shared content into separate asciidoc files and using an asciidoc include to pull in the content. That way, we maintain the content in one place, and the changes get pulled into the doc for each Beat. 

The shared asciidoc files would live in a directory at the same level as the beats (directory name TDB...I would like your input on naming).

The focus of the Beats Platform Reference would then shift a bit. It would describe how to get up and running with the ELK stack (with specific versions that work well with Beats), and on developing new Beats. 

WDYT? I'd like to implement this for 1.1 if you agree.

**Comment by monicasarbu** [comment]
That's a great idea and indeed it's something that we can do once we have only one repository. I think the main problem is that we will have outdated links in the old documentation.
@tsg knows more here.

**Comment by dedemorton** [comment]
@monicasarbu When I create the shared files and add the include statements, I'll take care of fixing any links in the Beats reference documentation, so there are no worries there...unless you are thinking about other doc that might link to the Beats config info in the Platform Ref.

**Comment by dedemorton** [comment]
Another note (mainly as a reminder to myself): The content about editing the beats.yml file to enable logstash output should probably be shared content that appears in the reference doc for each beat so users don't have to jump back and forth between documents. Ideally, users go to the platform reference to learn how to set up the ELK stack for beats...and then they go to the specific beat reference doc to learn how to install and set up the beat.

**Comment by dedemorton** [comment]
I have a small list of minor issues to resolve, but for the most part, I've resolved the structural issues with the fixes in this PR: https://github.com/elastic/beats/pull/542. 

There is one outstanding issue that @monicasarbu brought up when she reviewed the PR (copying it here for discussion): "I noticed that in the Filebeat docs, for example, in the Getting started guide, you still use links. There is a link to how to install Elasticsearch and Logstash instead of copying the text, similar with what you did for configurations. Is there any reason? I was thinking that after you copy the sections, we can just delete the Getting started guide from "Beats Platform Reference"." [note here that the "copying" is not a manual process; it's automated and single-sourced]

I actually prefer keeping the installation/configuration information about the ELK stack in the Platform Reference because this information is tangential to getting started with Beats. Not all users need to see the information (they might be existing users or they might have used other doc to get set up). And once they've set up the stack for one Beat, they won't have to repeat the steps for other Beats. Plus I'm concerned that adding the ELK installation content to the Beats Getting Started will make the topic too long.

The good news is that users who haven't installed the ELK stack will be directed to go to the Platform Reference to install the required software, and then they can go back to the Reference Guide and follow the steps in the Getting Started. They won't have to jump back to the Platform Reference once they've started installing and configuring the Beat.

As a future project, I'm planning to put together a Getting Started guide for the Elastic stack, which will probably make most of the GS content in the Platform Reference unnecessary anyhow (and what's left can live in the Getting Started for the Beats.

@tbragin WDYT? Does the current structure address your concerns?

**Comment by monicasarbu** [comment]
@dedemorton Sounds good your proposal. You convinced me it's better to have links instead of copying the text to each Beat. I prefer to have a small Getting started guide for each Beat. Thanks!

**Comment by dedemorton** [comment]
I am closing this issue. If @tbragin has additional feedback, I'll reopen. Thanks!

**Comment by tsg** [comment]
@dedemorton I think the current solution is already a great step forward, but I was wondering whether long term we want to move to a single asciidoc book, which we'd place top level in the repo under `docs`? One advantage would be that we would be able to use references rather than real links, which only get checked when the whole thing is built. 

This would mean that all sections move a step down (`=` becomes `==`, `==` becomes `===`, a.s.o), so that might be a problem, not sure. Otherwise, I guess the structure could remain mostly the same.

**Comment by dedemorton** [comment]
@tsg I plan to move all the docs to a single docs directory at some point, but having one asciidoc book has some limitations. For example, right now, when you search for one of the shared configuration settings, the search results provide context info that would be missing if all the content were in a single book. Sure the description of the option is the same, but we don't want people looking in the Packetbeat doc for information about configuring Topbeat. :-) 

![screen shot 2015-12-17 at 3 04 11 pm](https://cloud.githubusercontent.com/assets/14206422/11903845/ec7244d2-a570-11e5-8fd4-8aecd9c54d7d.png)

This problem also applies to searches for general conceptual stuff that might be the same across products.

Early next year, the pubs team will be looking at the design of the docs landing page to find ways to improve the user's experience finding our stuff, so that might be a time when we can revisit this question within the larger context of how we organize content in our library.
