### ISSUE TITLE
Riemann output

### ISSUE THREAD

**Issue by falzm** [elastic/libbeat#30]
Hi

I've started working on a [Riemann](http://riemann.io) libbeat output, and while I managed to get a working prototype I'm facing some difficulties working with the internals of libbeat. The Go bindings I'm using to send events to Riemann are [amir/raidman](https://github.com/amir/raidman), and the issue is that I'm passing libbeat's event (of `common.MapStr` type, which is an alias of `map[string]interface{}`) as [event attributes](https://github.com/amir/raidman/blob/master/raidman.go#L46), which is a `map[string]string` (serialized using Protobuf).

This should not not be a big issue in theory – I'd just have to convert `common.MapStr`'s values into strings using the `reflect/strconv` packages, which I did –, however when it comes to nested maps, there are conflicting types, for instance from the Packetbeat's http protocol handling: [headers are stored in a map[string]string](https://github.com/elastic/packetbeat/blob/master/protos/http/http.go#L58), thus preventing iterating recursively on an event's keys using `reflect`. My approach is to iterate over an event's entries to populate a `map[string]string` that will be sent to Riemann: [here](https://gist.github.com/falzm/90918abf45c5bd8cae8d) is my draft code (please bear with me, it's a work in progress and I'm not a professional developer) that doesn't compile because of that issue I'm facing, and I cannot see how to solve this.

I might be wrong in my approach or implementation, feel free to comment :)

**Comment by kimchy** [comment]
hey, the goal with beats is not the create another logstash with a breadth of outputs, as this reduces the whole lightweight focus of beats.

The idea is to work on Logstash dedicated output, using the lumberjack protocol, and from there, Logstash already has a riemann output.

**Comment by falzm** [comment]
I started working on this because I didn't want to use the ELK stack – and maybe not everyone wants to either. Well, based on your reply it looks like Packetbeat development plans are focused on the Elastic endgame and there's no room for open source contributions for other use cases.

**Comment by kimchy** [comment]
I tried to explain that the goal of Beats is not to create another Logstash, we already have one. By having support for multiple outputs, we are paving the way to the same reason why Logstash is tricky to use as a lightweight collector/shipper.

Once the native protocol is implemented between Beats and Logstash, you can do Beats -> Logstash -> Riemann.

**Comment by falzm** [comment]
I understand what you've said, I just don't get it. Why no just shut Packetbeat/libbeat down and implement the code straight into Lumberjack, then?

Before being "bought" by Elastic, Packetbeat was a nice and promising software: now it's just another means to Elasticsearch's end. It's quite sad to me.

**Comment by kimchy** [comment]
what do you mean by "straight" into lumberjack, lumberjack is a protocol, not an endpoint. Packetbeat (and Filebeat, and other beats) will use the lumberjack protocol to integrate directly to Logstash and stream data from it to all the outputs that Logstash supports.

Packetbeat supported Elasticsearch first, then Redis later to integrate with Logstash and it's various outputs and additional processing (where lumberjack protocol level integration would be better and this is where we are going to invest). Seeing this history, I find it hard to understand how you can claim it is being shut down, this makes very little sense.

**Comment by synhershko** [comment]
@kimchy logstash's main disadvantage is it being a heavy resource consumer. It's not just because of the number of outputs it has but mainly because of the way / language it's written in.

Riemann is becoming a more common way to dispatching events to ELK - mainly because of it's state machine capabilities. For some cases it is way more flexible and responsive than, say, Watcher. And for the cases where ELK is wanted for monitoring but with a light dispatcher (FileBeat for example), and Riemann on the front for throttling or triggering actions - requiring the non-lightweight logstash to be added to the stack (likely as a separate machine and maybe also a queue in front of it) just in order to do the lumberjack->riemann translation is simply an overkill.

With all this in mind, will you be accepting contributions that add Riemann as an output to libbeat?

**Comment by kimchy** [comment]
My concern is that this additional integrations will grow and grow (you have an opinion about the criticality of Rieman, I heard requests for at least 10 more outputs that Beats *must* have). Our goal is not to create another Logstash, and want to keep beats simple and lightweight. Setting up a logstash instance, now, with the new integration of beats to logstash, is very simple.

**Comment by synhershko** [comment]
I hear that concern. You might remember my take about logstash (=it's way to slow and heavy for a log shipper, and really needs to be rewritten from scratch) and therefore I'd actually be in favor of having beats as a replacement, or part of a replacement, for logstash. Go is a much better choice than JRuby, however you look at it.

As long as this doesn't happen for reasons, if I follow your advice on this thread, I'm left with one of these options:

1. Use filebeat to tail logfile(s) on a server, and have logstash on that same server just to receive the lumberjack output and forward it to Riemann. I might just as well have logstash tail the actual log file(s) at this point, and either way I end up with a logstash instance running on my mission critical servers - which I'd really like to avoid for obvious reasons.

2. Use filebeat and send its output to logstash for translation on a separate server, or a cluster of them. I believe you'd agree this is an overkill.

For the reasons of wanting to tail a logfile easily using a lightweight daemon, without requiring extra instances for lumberjack -> riemann translation, I would like to have a way to plug in to libbeat and provide my own outputs. If those outputs can be contributed back - all the better.

I'm sure there is a way we could leverage the excellent libbeat without being forced to use logstash. As always, I'll be happy to discuss further and contribute code back.

**Comment by kimchy** [comment]
the recommended way is to run all the different beats you have to a centralized Logstash that can forward the data to rieman. 

Logstash has more than 200 plugins, many of them outputs. It makes little sense to replicate this work, moreover, replicating this work will defeat the purpose beats were built in the first place. 

it is not about contributing code, it is about the spirit and goal of this project. And saying no as much as yes to asks that are easy to see will cause it to fail a year from now.

**Comment by mrkschan** [comment]
@synhershko, I'm new to Riemann. Do you know if there is any Riemann client that can receive events from `stdin`? libbeat has a `console` output where you can actually pipe that into another lightweight program for network transfer. So, packetbeat / filebeat acts as event collector while there is another program just for network transfer.

@kimchy, I agree that libbeat should have a minimal set of supported outputs. Though, I would like to know if libbeat shall support certain kind of plug-in interface (e.g. exposing event streams via unix domain socket). I believe that would provide greater flexibility than the `console` output for any custom setups.

**Comment by urso** [comment]
In general I would like to keep the number of output plugins at minimum for now (no matter what we will support in the future). We've done quite some in restructuring to the output pipeline in libbeat and would like to enhance even more (https://github.com/elastic/libbeat/issues/111) in upcoming releases. Adapting the already present output plugins to these changes did take quite some time already and redis have been left-behind for now (and is marked deprecated). Adding more output types right now will slow us down in upcoming improvements to libbeat + adds quite some testing overhead for us. Only maintaining the output types took more time and resource then any other work done to libbeat (besides focus was on other tasks). Using the console output as described by @mrkschan you can already process/filter events (collect, analyze) using your own scripts.

Plus Lumberjack is just a protocol for connecting the beat to some sink (Logstash by default). Why not have Lumberjack input plugin for Riemann? In the end it is about supporting one common protocol for data exchange.

So to speek, you can always create your custom beat from existing beats. The custom beat can 'register' your own output plugin just by importing the module the output is defined in the module. See default output registration in [publish.go](https://github.com/elastic/libbeat/blob/master/publisher/publish.go#L15). All beats are already 'pluggable' in a sense that you can basically combine all existing beats into one big custom build beat. For example see main function for [filebeat](https://github.com/elastic/filebeat/blob/master/main.go#L25) or [topbeat](https://github.com/elastic/topbeat/blob/master/main.go#L14) or [packetbeat](https://github.com/elastic/packetbeat/blob/master/main.go#L11). Just be aware, if you have your own custom output type, you will be responsible to keep it compatible to libbeat.

**Comment by gtrak** [comment]
Following the same train of though, I found a WIP java lumberjack protocol impl here: https://github.com/logstash-plugins/logstash-input-beats/blob/master/src/main/java/org/logstash/beats/Server.java

It might simplify a riemann integration.
