### ISSUE TITLE
bug: direction field values are incorrect

### ISSUE THREAD

**Issue by rshriram** [elastic/libbeat#300]
The direction field indicates whether a transaction was incoming (recorded at the server) or outgoing (recorded the client). In its current form, the value of the direction field is incorrect. It shows "in" for outgoing transactions and "out" for incoming transactions.

I have sent a pull request with the respective bugfix.

**Comment by andrewkroh** [comment]
Fixed in #301.

**Comment by andrewkroh** [comment]
Change log is now updated.
