### ISSUE TITLE
Elasticsearch output - making index name patterns configurable

### ISSUE THREAD

**Issue by gr0** [elastic/libbeat#318]
Hi, 
Could we make the Elasticsearch index names fully configurable in the output? Right now, we can specify the prefix and the date part is added automatically. Could we have the whole pattern configurable?

Or maybe I'm missing something and that is already supported?

Thanks.

**Comment by monicasarbu** [comment]
Currently, it is not possible to fully configure the index pattern, but I think it's a good idea.

**Comment by monicasarbu** [comment]
@gr0 Just curious, what do you plan to achieve in fully configuring the index pattern?

**Comment by otisg** [comment]
Awesome idea.  A log shipping tool should not force its users to name indices however it decided to name them.  I think it's cool to let people *optionally* specify YYYY-MM-DD type of thing, so this part of the index name can change automatically based on the current date, but that should be optional.

**Comment by kimchy** [comment]
the default should remain the same as it is today, obviously, as this is the right way to use it in the context of ES

**Comment by otisg** [comment]
+1 for meaningful defaults and another +1 for flexibility.

**Comment by gr0** [comment]
Agreed when it comes to defaults - they are very simple when it comes to out of the box functionality, but if we could have a bit more flexibility when it comes to patterns I would be very thankful :)

@monicasarbu I like Filebeat and ES output, but I need common indices naming for data coming from various sources. The other thing is I think the output would benefit from flexibility here :) 

Thanks for considering that option.

**Comment by megastef** [comment]
+1 any progress here? Prefix and date pattern must be configurable (e.g. having different index prefix for different applications or customers, ...). Is it possible to point libbeat to an alias, and don't use any date pattern?

**Comment by ruflin** [comment]
Closing this as I want to encourage you to continue the discussion here in this new issue in the beats repository: https://github.com/elastic/beats/issues/921
