### ISSUE TITLE
Filebeat: Beat for shipping log files

### ISSUE THREAD

**Issue by tsg** [elastic/libbeat#32]
Filebeat is meant to be the next iteration of the [Logstash-Forwarder](https://github.com/elastic/logstash-forwarder) (LSF).

Because LSF is also written in Go, and because our first priority is to avoid adding new bugs and removing features by mistake, we plan to reuse large parts of the LSF codebase. We will start a new Filebeat repository in which we will import the source code files from LSF.

The first release of Filebeat (targeted for Oct 2015) will be equivalent in functionality with the existing LSF. The semantics around guarantees (log lines are not lost, but might be duplicated) remain the same. Future releases might include enhancements like simple grepping, multi-line support, etc. The [filebeat](https://github.com/elastic/logstash-forwarder/labels/filebeat) label contains the LSF enhancement requests that we are consider adopting in Filebeat.

For this first release, we consider changing the codebase in the following areas:

### Main function, logging, signal handling, etc.

The Filebeat will be a Beat, which means implementing the Beater interface and using the libbeat modules for configuration, logging, signal handling, etc. The code in Filebeat will be split into modules to keep the `main` package at the minimum. We intend to add integration tests and improve the unit test coverage during this code reorganization.

### Publisher and protocol

The publisher part (Lumberjack implementation) will be moved into libbeat and transformed into a libbeat "output" plugin. This means other Beats will be able to make use of it as well. This also means the libbeat outputs need to have the optional "registrar" feature which means receiving acknowledgments when the next stage has processed each message.

As part of this change, we'll make encryption and client certificates authentication optional.

Time permitting, we'll try to implement better mechanisms for detecting when Logstash is too busy or temporarily unavailable, because this part is a large source of problems, but ideally keeping backwards compatibility. Future releases might contain a full rework of the protocol, switching to the pull model, better support for multiple logstash servers, etc.

### Config file

We plan to switch to YAML for configuration to match the other Beats, but keep the overall structure of the file. A tool to convert from the LSF configuration format to the Filebeat one will be provided.

On thing to keep in mind here is that LSF supports reading multiple configuration files from a `conf.d` folder. This is a feature we might consider adding to libbeat so it's available to all Beats.

### Packaging and others

We plan to use the same compiling / packaging infrastructure as for the other beats. Some aspects around logging, signal handling, init scripts etc. might also change as they will use the libbeat functions.

### Bug fixes

Time permitting, we'll try to solve some of the currently known issues with LSF. Here is a list of curated known [issues](https://github.com/elastic/logstash-forwarder/labels/bug).

**Comment by tsg** [comment]
I edited the description to update it with the current plans.

**Comment by ruflin** [comment]
Closing as filebeat now exists here: https://github.com/elastic/filebeat/
