### ISSUE TITLE
Update Developer guide for Interface changes

### ISSUE THREAD

**Issue by ruflin** [elastic/libbeat#330]
See:
* https://github.com/elastic/libbeat/pull/315
* https://github.com/elastic/topbeat/pull/141
* https://github.com/elastic/filebeat/pull/290
* https://github.com/elastic/packetbeat/pull/401

**Comment by monicasarbu** [comment]
@ruflin is there a reason Packetbeat doesn't show up here?

**Comment by ruflin** [comment]
@monicasarbu Yes, because the PR is not done yet :-)
