### ISSUE TITLE
Configure output queue size

### ISSUE THREAD

**Issue by urso** [elastic/libbeat#337]
Default output queue size is 1000 elements. This is okish for packetbeat to deal with spikes, but bad for topbeat. If output plugins are stalled due to elasticsearch/logstash being unavailable memory usage will grow until internal queues fill up. For packetbeat and topbeat memory events queued up is given by N*(3+B) where N=queue size (all internal queues same size) and B=bulk_max_size. For topbeat this can easily grow > 100MB.

For additional details see [discuss](https://discuss.elastic.co/t/topbeat-does-not-drop-events/)

**Comment by monicasarbu** [comment]
Let's keep only discuss for now and decide later when to schedule it.

**Comment by tsg** [comment]
+1 to make it configurable and lower the default. I think we didn't expect it to be multiplied by the bulk size, then the 1000 doesn't make sense.

**Comment by urso** [comment]
Continue discussion in elastic/beats#516
