### ISSUE TITLE
Installation instructions in Beats Platform Reference do not include Windows install steps

### ISSUE THREAD

**Issue by dedemorton** [elastic/libbeat#343]
The directions for getting started currently do not include Windows steps for installing Elasticsearch, Logstash, and Kibana, but should.

https://www.elastic.co/guide/en/beats/libbeat/current/getting-started.html

**Comment by monicasarbu** [comment]
It's not very well that we copied the installation guides for Kibana, Elasticsearch and Logstash in the Beats guide, but I wanted to have a guide on how to install the entire ELK stack. We will probably move this in the future somewhere else, but for now we can keep as it is (and just add the steps on windows) or you can link to the installation guide of the projects into here if you prefer not to have duplicated documentation.

**Comment by dedemorton** [comment]
I actually think it's really useful to have one place where our users can go to learn how to install everything.  Until we have a getting started guide for the stack, I think we should keep this here.

**Comment by dedemorton** [comment]
This issue is resolved by https://github.com/elastic/beats/pull/452
