### ISSUE TITLE
Duplicate prevention by assigning unique event id at source

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/libbeat#350]
The Elastic Stack ingest components now support at-least-once delivery guarantee. In order to also support duplicate prevention, it would be useful if it was possible to configure all Beats to generate a unique event id at when an event is first generated. This could then be used as a document id when indexing into Elasticsearch and result in an update rather than a duplicate being created.

It would be good if a few different types were supported, but we should try to ensure that the default (if applicable) is an [efficient identifier from Elasticsearch's point of view](http://blog.mikemccandless.com/2014/05/choosing-fast-unique-identifier-uuid.html).

**Comment by ruflin** [comment]
@cdahlqvist Not sure if you added the issue here on purpose. This repo is not used anymore. Best open an issue in https://github.com/elastic/beats

**Comment by cdahlqvist** [comment]
I was not aware it is no longer in use. Will close and add to the existing issue there instead.
