### ISSUE TITLE
Configurable redis message queue size

### ISSUE THREAD

**Issue by urso** [elastic/libbeat#57]
Redis message queue has default size of 1000 elements. We should make this configurable and maybe choose a smaller limit.

**Comment by tsg** [comment]
Not only Redis, but the Elasticsearch output at least has this issue. I'm not sure about fileout.

**Comment by ruflin** [comment]
@urso Can this be closed?

**Comment by ruflin** [comment]
Seems to be related to: https://github.com/elastic/libbeat/issues/337

**Comment by urso** [comment]
Yes, let's close this one. #377 is more generic
