### ISSUE TITLE
Improve the ES output plugin

### ISSUE THREAD

**Issue by tsg** [elastic/libbeat#6]
There are some minimal requirements for the ES output plugin:

* Make sure ES output works well (scale, shield)
* Simple output using http, supporting: multi host, http+https, headers
* Verify shield and found works well
* Batching support
* Support for managing the ES template file

**Comment by elvarb** [comment]
Maybe a dumb question but why not just skip the elasticsearch output and put everything as tcp json through logstash? 

That way it's very little code for packetbeat, all elasticsearch output logic is in one place for all elastic products and queueing is possible.

**Comment by kimchy** [comment]
@elvarb the plan is to provide users with 2 options, either go directly to ES, or go to Logstash. A "dump" TCP output to logstash is not enough, that why Logstash has the lumberjack protocol to allow for more intimate communication with it (created for logstash-forwrader). The plan is to have (and enhance) the lumberjack protocol and provide it as a built in capability in libbeat.

**Comment by elvarb** [comment]
Nice plan 😁
