### ISSUE TITLE
Load template at startup

### ISSUE THREAD

**Issue by monicasarbu** [elastic/libbeat#62]
It would be useful to load the template at startup, before inserting any data in Elasticsearch. After starting packetbeat and inserting data into Elasticsearch, it becomes difficult to load the template as you need to delete the old data from Elasticsearch before loading the template. So, I think the easiest solution would be to load the template when packetbeat starts.

The same should apply for topbeat as well and for any other beats.

**Comment by ruflin** [comment]
beta4 label removed as I don't see this as critical for the release.

**Comment by tsg** [comment]
For reference, we should look at how Logstash configures this: https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-manage_template

**Comment by ruflin** [comment]
:+1: We should use the same config variable `manage_template: false` to disable this.

**Comment by mrkschan** [comment]
I didn't use index template before and don't know that it's non-trivial to apply a template if there is existing data in ES. My concern is that what will happen if the users upgrade their beat and the beat ships a new version of the index template? Would "automatic" template loading breaks anything?

**Comment by urso** [comment]
@mrkschan [reindexing](https://www.elastic.co/guide/en/elasticsearch/guide/current/reindex.html) will be required if new template is incompatible. Reindexing is also a good [reason to use aliases by default](https://www.elastic.co/guide/en/elasticsearch/guide/current/index-aliases.html).
