### ISSUE TITLE
Race Condition in Elasticsearch TopologyOutputer

### ISSUE THREAD

**Issue by andrewkroh** [elastic/libbeat#73]
The following two code locations have a race condition on the same map. One is reading the map and the other is changing the reference. Since swapping the map reference is not an atomic operation this could cause an issue.

https://github.com/andrewkroh/libbeat/blob/master/outputs/elasticsearch/output.go#L156
https://github.com/andrewkroh/libbeat/blob/master/outputs/elasticsearch/output.go#L278-278

[Race Detector Stacktraces](http://pastebin.com/raw.php?i=NLr2wdgr)

**Comment by urso** [comment]
maybe we can find the solution in here: https://golang.org/pkg/sync/atomic/

**Comment by andrewkroh** [comment]
@urso I used the `atomic.Value` from that package. Can you take a look at #74 . Thanks.
