### ISSUE TITLE
Disparity in TLS config for lumberjack and ES output plugin

### ISSUE THREAD

**Issue by urso** [elastic/libbeat#79]
ES relies on host configuration: https://www.elastic.co/guide/en/beats/packetbeat/current/_using_https_and_basic_authentication.html

Whereas lumberjack output plugin requires all TLS based configuration in config file.

Update output plugins to both support TLS via host configuration and optionally config file.

**Comment by urso** [comment]
PR #86

**Comment by monicasarbu** [comment]
Could you please update the documentation as well? I am moving this section to libbeat/doc/https.asciidoc in https://github.com/elastic/libbeat/pull/98

**Comment by monicasarbu** [comment]
Available here as well: https://github.com/elastic/packetbeat/pull/261

**Comment by monicasarbu** [comment]
Track the issue https://github.com/elastic/libbeat/issues/100

**Comment by monicasarbu** [comment]
Duplicated
