### ISSUE TITLE
time zone for Elasticsearch time index

### ISSUE THREAD

**Issue by urso** [elastic/libbeat#81]
index for elasticsearch uses timestamp of event to identify the index:

https://github.com/elastic/libbeat/blob/master/outputs/elasticsearch/output.go#L193

Which time-zone will the events timestamp be in? We want to ensure UTC always (or optional by config)?

**Comment by andrewkroh** [comment]
Two potential time zone issues were investigated.

1. Whether time stamps in event data are affected by time zone issues.
2. Whether the destination index for an event can be affected by time zone issues.

Time stamps written in events are [always marshaled to JSON in UTC](https://github.com/elastic/libbeat/blob/master/common/datetime.go#L18) format as long as they are of type `common.Time`. So no issue there.

The destination index (`beatname-YYYY-MM-DD`) could differ from the UTC based `timestamp` field contained in the event in some circumstances. For example if a beat creates a `timestamp` field using `time.Now()` and the machines time zone is ETC then there would be a period of time each day where events are routed to the previous day's index.
