### ISSUE TITLE
Reenable event filtering by improving interaction with publisher

### ISSUE THREAD

**Issue by urso** [elastic/libbeat#94]
Combine/improve event filtering with publisher pipeline.

Question is: shall filtering happen before sending events to the publisher pipeline, or do we want to enhance the publisher pipeline so filtering can happen inside the pipeline hiding the fact events are filters from the actual beat (I would prefer the later one).

**Comment by andrewkroh** [comment]
From a client perspective it seems like it would be simpler to hide the filtering. Are there any strong reasons that a beat implementation would want/need to know about the filtering? (None come to mind.)

**Comment by urso** [comment]
+1

Plus: all event filtering will be up to the operator.

**Comment by andrewkroh** [comment]
https://github.com/elastic/packetbeat/pull/255#discussion-diff-40098149

**Comment by ruflin** [comment]
This could also relate to: https://github.com/elastic/libbeat/issues/336

**Comment by urso** [comment]
Yes, related.
